#!/usr/bin/env node
/**
 * Generates src/data/goaMLAs.js and src/data/goaMPs.js from the backend's
 * verified datasets (backend/src/data/goa_mlas.json, goa_voter_profiles.json),
 * so the frontend and backend rosters can never drift.
 *
 *   node frontend/scripts/gen_goa_data.js
 *
 * Re-run after any change to the backend roster (by-election, defection,
 * reshuffle). Vacant seats are emitted with mla/party "Vacant" and
 * `vacant: true`, so every screen that prints them still renders.
 */
const fs = require('fs');
const path = require('path');

const DATA = path.join(__dirname, '..', '..', 'backend', 'src', 'data');
const OUT = path.join(__dirname, '..', 'src', 'data');

const mlas = JSON.parse(fs.readFileSync(path.join(DATA, 'goa_mlas.json'), 'utf8'));
const aliases = JSON.parse(fs.readFileSync(path.join(DATA, 'goa_constituency_aliases.json'), 'utf8')).aliases;

const rows = mlas.map((m) => ({
  acNumber: m.ac_number,
  constituency: m.constituency,
  key: m.key,
  district: m.district,
  taluka: m.taluka,
  lokSabha: m.lok_sabha,
  reserved: m.reserved_category || null,
  mla: m.vacant ? 'Vacant' : m.mla,
  party: m.vacant ? 'Vacant' : m.party,
  alliance: m.vacant ? '—' : m.alliance,
  vacant: !!m.vacant,
  criminalCases: m.vacant ? null : m.criminalCases,
  education: m.vacant ? null : m.education,
  assets: m.vacant ? null : m.assets,
  liabilities: m.vacant ? null : m.liabilities,
}));

const tally = rows.reduce((acc, r) => { acc[r.party] = (acc[r.party] || 0) + 1; return acc; }, {});

const mlaModule = `// AUTO-GENERATED by frontend/scripts/gen_goa_data.js from
// backend/src/data/goa_mlas.json — do not edit by hand.
// Goa Legislative Assembly, 40 seats. 2022 election affidavits (ADR); current
// party as of Sep 2026 (the eight Sep 2022 Congress→BJP defections applied).
// Tally: ${Object.entries(tally).map(([p, n]) => `${p} ${n}`).join(', ')}.
//
// Each record: acNumber, constituency (ECI name), key (normalized lookup),
// district (current, incl. Kushavati), taluka, lokSabha, reserved, mla, party,
// alliance, vacant, criminalCases, education, assets, liabilities.

export const GOA_MLAS = ${JSON.stringify(rows, null, 2)};

export const normalizeConstituencyKey = (name) =>
  String(name || '')
    .normalize('NFD')
    .replace(/[\\u0300-\\u036f]/g, '')
    .toLowerCase()
    .replace(/\\([^)]*\\)/g, ' ')
    .replace(/[^a-z0-9]/g, '')
    .trim();

// Alternate spellings (Konkani / Marathi / Portuguese-era) → ECI key.
// From backend/src/data/goa_constituency_aliases.json (shared with the backend).
const CONSTITUENCY_ALIASES = ${JSON.stringify(aliases, null, 2)};

export const MLA_BY_KEY = GOA_MLAS.reduce((acc, m) => {
  acc[m.key] = m;
  acc[normalizeConstituencyKey(m.constituency)] = m;
  return acc;
}, {});

export const getMlaByConstituency = (name) => {
  const k = normalizeConstituencyKey(name);
  return MLA_BY_KEY[k] || MLA_BY_KEY[CONSTITUENCY_ALIASES[k]] || null;
};

export default GOA_MLAS;
`;

const mps = [
  { lsId: 'northgoa', lsName: 'North Goa', mp: 'Shripad Yesso Naik', party: 'BJP', alliance: 'NDA' },
  { lsId: 'southgoa', lsName: 'South Goa', mp: 'Capt. Viriato Fernandes', party: 'INC', alliance: 'INDIA' },
];

const mpModule = `// AUTO-GENERATED by frontend/scripts/gen_goa_data.js — do not edit by hand.
// Goa 2024 Lok Sabha results — 2 seats (BJP 1, INC 1). Mirrored in
// backend/src/config/politicalData.js; keep the two in sync.
//
// \`lsId\` matches the keys of backend/src/data/goa_ls_to_ac.json.

export const GOA_MPS = ${JSON.stringify(mps, null, 2)};

const normalize = (s) => String(s || '').toLowerCase().replace(/[^a-z0-9]/g, '');

export const MP_BY_LS_ID = GOA_MPS.reduce((acc, m) => {
  acc[m.lsId] = m;
  return acc;
}, {});

const MP_BY_LS_NAME = GOA_MPS.reduce((acc, m) => {
  acc[normalize(m.lsName)] = m;
  return acc;
}, {});

export const getMpByLsId = (lsId) => MP_BY_LS_ID[normalize(lsId)] || null;

export const getMpByLsName = (name) => MP_BY_LS_NAME[normalize(name)] || null;

export default GOA_MPS;
`;

fs.writeFileSync(path.join(OUT, 'goaMLAs.js'), mlaModule);
fs.writeFileSync(path.join(OUT, 'goaMPs.js'), mpModule);
console.log(`wrote goaMLAs.js (${rows.length} seats: ${JSON.stringify(tally)}) and goaMPs.js (${mps.length} seats)`);
